enum ActionTypes {
  GENERATE_WINNER_COMBINATION = "GENERATE_WINNER_COMBINATION",
  SET_FIRST_PLAYER_CURRENT_SELECTED_CELLS = "SET_FIRST_PLAYER_CURRENT_SELECTED_CELLS",
  SET_SECOND_PLAYER_CURRENT_SELECTED_CELLS = "SET_SECOND_PLAYER_CURRENT_SELECTED_CELLS",
}

export default ActionTypes;
